-- Create branch_scopes table
CREATE TABLE IF NOT EXISTS branch_scopes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id VARCHAR(255) NOT NULL,
  scope VARCHAR(255) NOT NULL,
  scope_key VARCHAR(255) NOT NULL,
  essential_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 